.github/workflows/check-dist.yml, .github/workflows/sample-workflow.yml, README.md
This PR changes the following:
- Adds `if: ${{ github.event.issue.pull_request }}` to the docs and sample workflow to make our Action exit quickly if it doesn't need to run
- Removes `issues: write` as it is not needed
- Adds `if: ${{ steps.branch-deploy.outputs.continue == 'true' }}` to sample checkout command
=> Update docs and sample workflow

README.md, docs/usage.md
This pull request adds a basic usage guide for the Action and also updates the main readme with updated permissions and reasoning for the changes
=> Usage Guide

README.md, docs/examples.md
This pull request adds documentation for common deployment targets that developers are using in the wild today.
Documentation is added for the following services:
- Terraform
- Heroku
- Railway
- SSH
- Cloudflare Pages
- Cloudflare Workers
=> Examples Documentation

README.md, docs/usage.md
This pull request adds rollback details and examples to this repository's documentation
=> Rollback Docs

.github/workflows/sample-workflow.yml, README.md, docs/examples.md
Updates documentation around required permissions for the Action
=> update documentation around permissions

.github/workflows/ISSUE_TEMPLATE/bug.yml
This pull request adds an issue template for bug reports
=> Bug Template

__tests__/functions/actions-status.test.js, __tests__/functions/admin.test.js, __tests__/functions/context-check.test.js, __tests__/functions/deployment.test.js, __tests__/functions/environment-targets.test.js, __tests__/functions/identical-commit-check.test.js, __tests__/functions/post.test.js, __tests__/functions/prechecks.test.js, __tests__/functions/string-to-array.test.js, __tests__/functions/trigger-check.test.js, __tests__/main.test.js
This pull request greatly improves unit tests throughout the repository
=> Test Framework Improvements 🧪 

.github/workflows/package-check.yml, docs/examples.md
This pull request updates the `docs/examples.md` document
=> Examples Docs Updates

.github/workflows/codeql-analysis.yml, .github/workflows/lint.yml, .github/workflows/package-check.yml, .github/workflows/test.yml
This pull request updates all Actions workflows
=> Update all Actions Workflows

README.md, docs/examples.md
Update main readme to point to more examples. This PR also update the 'Multiple Jobs' example
=> More docs updates

.github/config/exclude.txt, .github/workflows/actions-config-validation.yml
Upgrades the json-yaml-validate Action to `v1.3.0`
=> Upgrade yaml validation

docs/unlock-on-merge.md
This pull request updates the documentation for the "Unlock On Merge Mode" page.
=> update 'Unlock On Merge Mode' docs

package-lock.json
This pull request updates all node dependencies with `npm update`
=> Node Dependencies

package-lock.json
This pull request updates internal node packages via `npm update`
=> node package updates

README.md, docs/custom-deployment-messages.md
This pull request contains documentation updates pointed at the `v7.1.0` release
=> Documentation Updates

.github/config/exclude.txt, .github/workflows/actions-config-validation.yml, .github/workflows/codeql-analysis.yml, .github/workflows/lint.yml, .github/workflows/package-check.yml, .github/workflows/test.yml, README.md, docs/examples.md, docs/merge-commit-strategy.md
This pull request updates Action workflow versions and the references to them in documentation files
=> Update Action Workflows

docs/examples.md
This pull request updates the `docs/examples.md` page
---
related: https://github.com/github/branch-deploy/issues/218
=> Update Examples Documentation

package-lock.json, package.json
This pull request updates internal node deps that this Action relies upon and removes some metadata from the `package.json` file that are not needed
=> node deps and package cleanup

package-lock.json
This PR updates all internal node packages that this Action relies upon.
=> update all node packages

package-lock.json
This pull request updates all internal node dependencies that this project relies upon.
=> Node Updates
